# Generated by Django 4.2.4 on 2024-09-15 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractivitylog',
            old_name='user',
            new_name='student',
        ),
    ]
