# Generated by Django 4.2.4 on 2024-09-15 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('activity', '0002_rename_user_useractivitylog_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
    ]
